### ISSUE TITLE
Blurred results

### ISSUE THREAD

**Issue by franalbani** [Stability-AI/stability-sdk#11]
I've noticed that sometimes, some returned samples are completely blurred. This happens in DreamStudio and with `client.py`

See an example generated with `-C 12 --show -n 4 -s 10 'lovecraft holding a book, 16 bit color, game art, pixelated'`
![generation-7b937860-572a-401d-9d87-3f413b693184:0:1-9f7f5c75-f2ce-4828-81c3-4f8beee5d246-6](https://user-images.githubusercontent.com/13975308/186778018-5c550229-c86a-4678-b036-142f2cad388d.png)

```
pip freeze
grpcio==1.47.0
grpcio-tools==1.47.0
Pillow==9.2.0
protobuf==3.20.1
python-dotenv==0.20.0
python-magic==0.4.27
six==1.16.0
stability-sdk==0.1.1
```

Is this an expected behavior?

**Comment by MajorTal** [comment]
They have a classifier trying to identify nudity at the output. For some reason they don't expose this flag in the API. It is annoying.

**Comment by franalbani** [comment]
Thanks @MajorTal .

The example I showed was returned with a `.json` file that confirms that it was censored because the concept "dick" exceded the 0.2 threshold:

```json
{
  "categories": [
    {
      "name": "nsfw",
      "concepts": [
        {
          "concept": "sexual",
          "threshold": 0.1439209
        },
        {
          "concept": "nude",
          "threshold": 0.18444824
        },
        {
          "concept": "sex",
          "threshold": 0.18579102
        },
        {
          "concept": "18+",
          "threshold": 0.1850586
        },
        {
          "concept": "naked",
          "threshold": 0.16833496
        },
        {
          "concept": "nsfw",
          "threshold": 0.18139648
        },
        {
          "concept": "porn",
          "threshold": 0.1817627
        },
        {
          "concept": "dick",
          "threshold": 0.20031738
        },
        {
          "concept": "vagina",
          "threshold": 0.15979004
        },
        {
          "concept": "explicit content",
          "threshold": 0.16271973
        },
        {
          "concept": "uncensored",
          "threshold": 0.16247559
        },
        {
          "concept": "fuck",
          "threshold": 0.19152832
        },
        {
          "concept": "nipples",
          "threshold": 0.1583252
        },
        {
          "concept": "visible nipples",
          "threshold": 0.13623047
        },
        {
          "concept": "naked breasts",
          "threshold": 0.1508789
        },
        {
          "concept": "areola",
          "threshold": 0.12597656
        }
      ]
    }
  ],
  "exceeds": [
    {
      "name": "nsfw",
      "concepts": [
        {
          "concept": "dick",
          "threshold": 0.20031738
        }
      ]
    }
  ],
  "realizedAction": "ACTION_OBFUSCATE"
}
```

**Comment by franalbani** [comment]
I don't know if this is the correct place for complaining but, I'm losing a lot of credits because of this.

**Comment by dmarx** [comment]
@franalbani blurred results don't deduct credits. can you double check? if you're sure credits are being consumed, could you maybe describe your experience in a bit more detail in case your usage falls into some sort of edge case we haven't considered?

**Comment by franalbani** [comment]
@dmarx you are right! I didn't bother to check. My apologies.
Thanks!

Is it still unavailable the option to disable the filter?

**Comment by damonamyx** [comment]
> I don't know if this is the correct place for complaining but, I'm losing a lot of credits because of this.

me too

there are real implications for IP rights since a completed render is yours as of its completion. no third party has a superior right that would allow them to block you from what you paid for and created.

**Comment by FatKrab** [comment]
doesnt even have to be a breast. I once was generating a shrek prompt and, since the ai decided to draw him shirtless, it was blurred. And same thing occured when i requested something dress related.

Although i do see why the AI would respond this way, the filters input dont take on accountability the difrences between encountering nsfw in the prompt/image and a error in the analisys/generation

**Comment by kawada711** [comment]
WTF IS THIS BLURRING CRAP?!?!?!?! ARE YOU FKIN SERIOUS??! YOU ARE DEDUCTING CREDITS AND BLURRING COMPLETELY NORMAL IMAGES????!?! CANNOT EVEN GENERATE GIRLS OF MY AGE! FKIN NONSENSE
