### ISSUE TITLE
feature request: supporting negative prompts 

### ISSUE THREAD

**Issue by amrakm** [Stability-AI/stability-sdk#138]

**Comment by imperator-maximus** [comment]
With the new 2.0 model negative prompts are key to get any results. I am getting a server error back while using a negative weight right now.

**Comment by benrugg** [comment]
@imperator-maximus is there a way to use negative weights/prompts in the command line with the 1.4 or 1.5 model?

**Comment by imperator-maximus** [comment]
@benrugg I do not know about the command line tools. But negative prompts are supported by API now as far I know for all models I guess.

**Comment by benrugg** [comment]
@imperator-maximus Yeah, I switched over the REST API on the day it came out in alpha. And I implemented negative prompts in it. Thanks for letting me know, though!

**Comment by arashmh** [comment]
Is the negative prompt also available on stability-sdk python?

**Comment by benrugg** [comment]
@arashmh as far as I know, it's not. I think Stability is trying to move away from the grpc sdk and towards the REST API. Feel free to get on the Stable Diffusion discord (api channel) and ask, though!

**Comment by arashmh** [comment]
@benrugg That's a reasonable move if they move everything to a REST API.. 
There is this option for multiprompting in python SDK, which allows  assigning negative weight to parts of the prompt. Not sure if that's the same thing as negative prompting we see in other implementations of the stable diffusion

**Comment by benrugg** [comment]
Ah, gotcha. If multiple prompts were added recently, then you should be able to assign a negative weight, the same as in the REST API.

**Comment by arashmh** [comment]
Perfect.. then that should be it.. ill give it a go

**Comment by jerrychidata** [comment]
See example for using multiprompt including negative prompts: https://platform.stability.ai/docs/features/multi-prompting

**Comment by sanealytics** [comment]
Hmm. I get `TypeError: prompt must be a string or generation.Prompt object`
I guess its not in the release yet.

**Comment by ChristopherValore** [comment]
Closing this issue due to the implementation of multi-prompting with weights as can be found here: 
https://platform.stability.ai/rest-api#tag/v1generation/operation/textToImage
https://platform.stability.ai/docs/getting-started/typescript-client#helpers
https://platform.stability.ai/docs/features/multi-prompting
