### ISSUE TITLE
Interfaces folder empty after git clone

### ISSUE THREAD

**Issue by edmonto** [Stability-AI/stability-sdk#152]
After following the instructions on the Stability Python Documentation (https://platform.stability.ai/docs/getting-started/python-sdk#clone-stability-sdk-repo) I run into this issue after the last command:

`(pyenv) edi@Edis-MacBook-Pro stability-sdk % python3 -m stability_sdk.client -W 512 -H 512 "A stunning house."
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/edi/Documents/Coding/stability-sdk/src/stability_sdk/client.py", line 28, in <module>
    import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation
ModuleNotFoundError: No module named 'stability_sdk.interfaces.gooseai'`

I looked through the folders and realized that the /stability-sdk/src/stability_sdk/interfaces folder is empty, vs when I check on Github it has some of the dependencies that are missing in the error message above. 

How should I clone the repo so that the interfaces folder is cloned correctly? I didn't have any other error messages while cloning or setting up the Python environment.

**Comment by kakamove6** [comment]
same question

**Comment by dmarx** [comment]
Thanks for bringing this to our attention, the sdk installation instructions have been updated to address this issue. See updated install instructions here: https://platform.stability.ai/docs/getting-started/python-sdk
