### ISSUE TITLE
Getting different results with the same seed

### ISSUE THREAD

**Issue by stawiski** [Stability-AI/stability-sdk#169]
Hi,

I'm using python SDK and getting different results while using the same seed between stability python SDK and Dreambooth UI.
I'm expecting python SDK to produce the same image for the same prompt + seed + configuration, however the image comes out different.

Here's what I've tried:

Dreambooth:
![image](https://user-images.githubusercontent.com/26871388/212445253-e021d131-611f-4c42-b292-16d0c4079f6b.png)

Python SDK:
```
python -m stability_sdk --seed 1671915829 -n 1 --engine "stable-diffusion-v1-5" --steps 30 --cfg_scale 7  "lion head smiling"
```
![image](https://user-images.githubusercontent.com/26871388/212445316-f580c823-2e20-463a-9500-6dc6fe756f43.png)

Cheers

**Comment by sedetweiler** [comment]
CLIP based results are non-deterministic, so you will get a slightly
different result. Also, the video hardware can also lead to differences
depending on your situation. In this case, CLIP is probably the cause of
this variation.

**Comment by stawiski** [comment]
Hey @sedetweiler, I used Dreambooth instead of running this on my own hardware.
And you're right, **I do get the same picture when I disable "CLIP Guidance" in Dreambooth.**

However, I can't information in the SDK about CLIP guidance, does this mean this feature is only available via web in Dreambooth?

**Comment by pharmapsychotic** [comment]
@stawiski you can use CLIP guidance with the SDK. Check out the StabilityInference generate method and it has parameters:

```
        guidance_preset: generation.GuidancePreset = generation.GUIDANCE_PRESET_NONE,
        guidance_cuts: int = 0,
        guidance_strength: Optional[float] = None,
        guidance_prompt: Union[str, generation.Prompt] = None,
        guidance_models: List[str] = None,
```

Just pass generation.GUIDANCE_PRESET_FAST_BLUE for example for the guidance_preset (you can leave the others at their defaults). As @sedetweiler mentioned though when using CLIP guidance you won't get back the same result each time even if you use the same seed.

**Comment by stawiski** [comment]
@pharmapsychotic you're right! Thanks!
