### ISSUE TITLE
Integration with other models

### ISSUE THREAD

**Issue by TimFinnigan** [Stability-AI/stability-sdk#175]
Hello! Awesome work and quick question.

The available engines listed in the boilerplate SDK code are:
```
# Available engines: stable-diffusion-v1 stable-diffusion-v1-5 stable-diffusion-512-v2-0 stable-diffusion-768-v2-0
# stable-diffusion-512-v2-1 stable-diffusion-768-v2-1 stable-inpainting-v1-0 stable-inpainting-512-v2-0
```

Are there plans to allow simple integration of models build on Stable Diffusion? (for example: [Protogen](https://huggingface.co/darkstorm2150/Protogen_x3.4_Official_Release))

**Comment by ChristopherValore** [comment]
Hi there! @TimFinnigan Please accept our apology for the delay in response. At the moment we're only supporting the models that we have listed, if that changes however we'll be sure to note it on https://platform.stability.ai in an update.
