### ISSUE TITLE
not able to install with python 3.11.x

### ISSUE THREAD

**Issue by rvorias** [Stability-AI/stability-sdk#176]
python 3.11.1 doesn't seem to be able to install grpcio==1.48.1
(ubuntu)

grpcio==1.51.1 does work

Can you bump the grpcio version?

**Comment by mariorojas** [comment]
got the same error with python 3.11.2 so I guess former title "not able to install with python 3.11" was ok

**Comment by ChristopherValore** [comment]
Hi there! @rvorias @mariorojas At the moment we aren't supporting 3.11.x, but versions between 3.7 and 3.10 should work.

**Comment by ChristopherValore** [comment]
@rvorias Happy to hear that you were able to get it running! At the moment however, to my knowledge we are only testing compatibility between versions 3.7 and 3.10 for our releases.

**Comment by palp** [comment]
Resolved with #209
