### ISSUE TITLE
How to get "STABILITY_KEY" data? Thanks.

### ISSUE THREAD

**Issue by yinjiaoyuan** [Stability-AI/stability-sdk#19]
How to get "STABILITY_KEY" data? Thanks.

**Comment by dmarx** [comment]
1. log in to https://beta.dreamstudio.ai, create an account if necessary.
2. Click on the circular icon in the top right corner to activate a drop down menu
3. click on "Membership"
4. click on the "API Key" tab

The text string that begins `sk-` is your STABILITY_KEY. 

Treat this value with the same care as you would treat a password.
