### ISSUE TITLE
Node.js support & docs

### ISSUE THREAD

**Issue by transitive-bullshit** [Stability-AI/stability-sdk#191]
The readme mentions JS/TS support and links to https://github.com/Stability-AI/stability-sdk/tree/main/src/js which 404s.

Would love to use the official SDK from JS/TS. Thanks! 🙏

**Comment by ChristopherValore** [comment]
Hi there! @transitive-bullshit Please be sure to drop by our Platform site here: https://platform.stability.ai/docs/getting-started/typescript-client to learn more about how to use our current implementation of the API with TS.

**Comment by transitive-bullshit** [comment]
Thanks @ChristopherValore 

This repository's readme contains a link which 404s for "JavaScript/TypeScript", which you guys should probably fix 😉 

<img width="928" alt="CleanShot 2023-03-24 at 16 32 00@2x" src="https://user-images.githubusercontent.com/552829/227645493-268f4995-6265-4c00-a5b6-5b9cede66981.png">

**Comment by ChristopherValore** [comment]
Nice catch, thanks for pointing that out!

> Thanks @ChristopherValore
> 
> This repository's readme contains a link which 404s for "JavaScript/TypeScript", which you guys should probably fix 😉
> 
> <img alt="CleanShot 2023-03-24 at 16 32 00@2x" width="928" src="https://user-images.githubusercontent.com/552829/227645493-268f4995-6265-4c00-a5b6-5b9cede66981.png">

**Comment by transitive-bullshit** [comment]
Awesome; thanks! 🙏
