### ISSUE TITLE
T2IAdapterParameters not present in generaion_pb2

### ISSUE THREAD

**Issue by jfdelgad** [Stability-AI/stability-sdk#250]
The generaion_pb2 is present in the [API interface repo](https://github.com/Stability-AI/api-interfaces/blob/6ccdf64141b19a278f96adb89322117041f68ce9/gooseai/generation/generation_pb2.py), but the SDK repository points to an older version of the API interface of it where T2IAdapterParameters is not defined.

Does this mean that the SDK does not support the use of the T2IAdpaters? if so, is there a plan to support this?

**Comment by satsumas** [comment]
Well spotted!

We will update the submodule pointer of the SDK to the head of Interfaces and enable support for T2I adapters very soon. The current SDK doesn't yet support them.

**Comment by jfdelgad** [comment]
> Well spotted!
> 
> We will update the submodule pointer of the SDK to the head of Interfaces and enable support for T2I adapters very soon. The current SDK doesn't yet support them.

Do you have any estimation for this, are these weeks, or months?

Also, if the SDK does not support this yet, is there a way to do this directly by calling the API, given that the interface already exists?

**Comment by satsumas** [comment]
It should be in the order of days.

Using the adapters requires more code to be merged server-side, which will happen when the feature is released.

**Comment by jfdelgad** [comment]
@satsumas is there any update about this?

**Comment by jfdelgad** [comment]
> It should be in the order of days.
> 
> Using the adapters requires more code to be merged server-side, which will happen when the feature is released.

Is there any update about this,  is T2IAdapter available already?

**Comment by jfdelgad** [comment]
> It should be in the order of days.
> 
> Using the adapters requires more code to be merged server-side, which will happen when the feature is released.

is there any update on this @satsumas ?

**Comment by jfdelgad** [comment]
never mind, I can see that you have already released a new version with those changes. thank you!

**Comment by Rikelai** [comment]
Hey @jfdelgad, I was looking for a way to add extras params to image generation api. In docs I read about this "extras" params where you can add struct object. I'm using rest api and trying to pass adapter. So i append to my formData: "extras" as a stringinfied object with 
{
adapter_type: "DEPTH",
adapter_strength: 1,
adapter_init_type: "IMAGE"
}
But no effect on image generation.
Could you show me how to successfully pass data ?
Thank you !

**Comment by pharmapsychotic** [comment]
@Rikelai sorry the feature wound up never released so it won’t work in the SDK or through REST.

**Comment by Rikelai** [comment]
@pharmapsychotic thank you for your answer, so from my understanding what is ready client side doesn't match server side ?
