### ISSUE TITLE
in nbs there is only python tutorial, how to use with nodejs?

### ISSUE THREAD

**Issue by MASSKAgithub** [Stability-AI/stability-sdk#26]
*No fucking description provided*

**Comment by jakiestfu** [comment]
I wrote this here https://github.com/jakiestfu/stability-ts

**Comment by dmarx** [comment]
we now have a separate repository for the js/ts client: https://github.com/Stability-AI/stability-sdk-js

**Comment by MASSKAgithub** [comment]
Nice error 404, showing, you know it's not so hard to put it publicly available

**Comment by dmarx** [comment]
my bad, didn't realize the js sdk wasnt public yet. we'll be releasing that soon, sorry for the confusion.

**Comment by Abel1011** [comment]
> my bad, didn't realize the js sdk wasnt public yet. we'll be releasing that soon, sorry for the confusion.

Hi, do you have an approximate release date for the js repository?

**Comment by jchirik** [comment]
> my bad, didn't realize the js sdk wasnt public yet. we'll be releasing that soon, sorry for the confusion.

^^ seconded, could also use a timeline on the JS SDK!!

**Comment by ChristopherValore** [comment]
Hi everyone! In case anyone ends up finding this in the future, we recently added a section to Platform that should help you get started using our API with NodeJS / TypeScript here: https://platform.stability.ai/docs/getting-started/typescript-client 

Any future releases regarding a JS SDK or implementation will be added onto Platform, thank you!
