### ISSUE TITLE
Unable install grpcio 1.53.0

### ISSUE THREAD

**Issue by zeonagames** [Stability-AI/stability-sdk#275]
I am getting error when I install grpcio 1.53.0,  I have already 1.60.1 but It doesnt work with stabilityai-sdk.

 ERROR: Failed building wheel for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

How can I fix this ?

**Comment by fygy10** [comment]
you need to use an older version of python: 3.10 or 3.11 (in a virtual environment). grpcio 1.53 is not compatible with the newest python 31.12 it seems
