### ISSUE TITLE
Cannot find reference 'finetune'

### ISSUE THREAD

**Issue by wookkl** [Stability-AI/stability-sdk#291]
![image](https://github.com/user-attachments/assets/8171f72a-edc2-452e-a0de-a0620ebc4aa0)

### Can not find finetune.py in source code

https://next.platform.stability.ai/docs/features/fine-tuning#setup-environment
I am doing this example.

**Comment by andreybleme** [comment]
Were you able to figure it out @wookkl ?

Facing the exact same issue here :(
