### ISSUE TITLE
ModuleNotFoundError: No module named 'stability_sdk.finetune'

### ISSUE THREAD

**Issue by andreybleme** [Stability-AI/stability-sdk#300]
Hi all,

I'm trying to run the fine-tuning example provided by the docs (https://next.platform.stability.ai/docs/features/fine-tuning#api-connection), and getting an error with the dependency "stability_sdk.finetune":

```
Traceback (most recent call last):
  File "/finetuning.py", line 9, in <module>
    from stability_sdk.finetune import (
ModuleNotFoundError: No module named 'stability_sdk.finetune'
```

I have successfully installed the stability-sdk pip dependency.
```
$ pip install stability_sdk
```

But python can't find `stability_sdk.finetune`. 

Has anyone also faced this issue? Is this SDK still maintained?

Thank you!

**Comment by pharmapsychotic** [comment]
Sorry, the fine-tuning service was only available in a limited beta and has been retired. The correct link for StabilityAI platform docs is https://platform.stability.ai/ 

> Has anyone also faced this issue? Is this SDK still maintained?

The REST API should be used and only the old SDXL engine is still available via gRPC and this SDK.
