### ISSUE TITLE
Is generation.proto up to date?

### ISSUE THREAD

**Issue by cou929** [Stability-AI/stability-sdk#32]
`generation_pb2.py` is re-generated in https://github.com/Stability-AI/stability-sdk/pull/27/commits/62122c61da9c13a56301026419ef4685a7e2081f (https://github.com/Stability-AI/stability-sdk/pull/27) but [generation.proto](https://github.com/Stability-AI/stability-sdk/blob/8dd359c79ecf004913ba1e7693c5657933092926/src/proto/generation.proto) looks like not updated yet.

Could you commit the latest proto file? Because I've been using this proto file to call API in other language.

**Comment by cou929** [comment]
Does it move to https://github.com/Stability-AI/api-interfaces ?

**Comment by dmarx** [comment]
yes you are 100% correct. need to update this repo to include api-interfaces as a submodule dependency. the most up-to-date proto files are over there, will probably update our build process next week to automatically keep the sdk up to date with the API
