### ISSUE TITLE
the latest version code doesn’t work on my mac 

### ISSUE THREAD

**Issue by leeluo** [Stability-AI/stability-sdk#33]
After I pull the latest code (from main branch), I execute the following command, then i got this error

- generation.proto: A file with this name is already in the pool.

![image](https://user-images.githubusercontent.com/26829993/189265730-d7a05f89-6160-4a4a-8db3-74559f0d83fa.png)

Then I tried the following commands to solve the problem
-  pip uninstall protobuf
-  pip install --no-binary protobuf protobuf

after, run 'python3 client.py -W 512 -H 512 "superman"', then i got this error
- Traceback (most recent call last):
  File "client.py", line 26, in <module>
    import stability_sdk.interfaces.gooseai.generation.generation_pb2_grpc as generation_grpc
  File "/root/miniconda3/lib/python3.8/site-packages/stability_sdk/interfaces/gooseai/generation/generation_pb2_grpc.py", line 5, in <module>
    import generation_pb2 as generation__pb2
  File "/root/code/stability-sdk/src/stability_sdk/interfaces/gooseai/generation/generation_pb2.py", line 75, in <module>
    _SCHEDULEPARAMETERS = DESCRIPTOR.message_types_by_name['ScheduleParameters']
KeyError: 'ScheduleParameters'
![image](https://user-images.githubusercontent.com/26829993/189266625-dc88c382-12cf-4e7e-93f6-fda0aed12a05.png)

What is the cause of the problem? How to fix it?

README.md has not updated the description of init_img, when will the description of the latest version be updated?

Looking forward to your reply. thanks

**Comment by dmarx** [comment]
i'm guessing the protobuf stubs the SDK carries with it need to be updated. we'll be updating the sdk to take the recently published api-interfaces repo as a submodule dependency soon, which should handle stuff like this (assuming I'm right about the cause of the issue)

**Comment by chigozienri** [comment]
@leeluo Could you try
```
pip uninstall stability-sdk
```
Then navigate to the repository root and
```
pip install -e .
```
?

Thanks!

**Comment by leeluo** [comment]
> 
it Works!!!  
Now I can use it normally, including initimage  
thanks for you to helped me a lot
