### ISSUE TITLE
js/ts sdk is outdated

### ISSUE THREAD

**Issue by kevinfaveri** [Stability-AI/stability-sdk#37]
just found out that we don't have ScheduleParameters used for init image on the js/ts SDK, thus we can't use correctly init image with the JS/TS image

**Comment by kevinfaveri** [comment]
Also another qs: how to build the TS/JS SDK from an updated proto? (I think the proto is also outdated, not only the JS/TS sdk, but anyway...)

**Comment by dmarx** [comment]
current js/ts stubs and build instructions can be found here: https://github.com/Stability-AI/api-interfaces
