### ISSUE TITLE
Python sdk import fails in demo colab (or any colab)

### ISSUE THREAD

**Issue by dmahlow** [Stability-AI/stability-sdk#42]
<img width="952" alt="Screenshot 2022-09-16 at 00 28 53" src="https://user-images.githubusercontent.com/489843/190520023-4b9419af-30e0-4e4b-a200-acb5263a1648.png">

To reproduce, go to demo colab and execute cells: https://colab.research.google.com/github/stability-ai/stability-sdk/blob/main/nbs/demo_colab.ipynb

**Comment by iainmck** [comment]
+1 - getting the same error... tried downgrading protobuf package (where DESCRIPTOR is imported from) as there was an [update](https://pypi.org/project/protobuf/#history) 2 days ago, but still got same error.

**Comment by iainmck** [comment]
Hey got it to work with forcing protobuf version: `pip install protobuf==3.20.1`
Can add to your requirements/environment file

**Comment by dmahlow** [comment]
Great! Can confirm this works.

**Comment by jape-dev** [comment]
@iainmck that fixed it for me too - thanks!

**Comment by dmarx** [comment]
@iainmck thanks so much for figuring out this fix! working on integrating it presently.

**Comment by polavishnu4444** [comment]
What is the grpcio-tools version you guys have that is compatible with the protobuf version hardcoded here?

I see this following error for the new version 0.2.4 one

There are incompatible versions in the resolved dependencies:
  protobuf<5.0dev,>=4.21.3 (from grpcio-tools==1.49.1->stability-sdk==0.2.4->test-stability (pyproject.toml))
  protobuf<4,>=3.20.2 (from stability-sdk==0.2.4->test-stability (pyproject.toml))

**Comment by dmahlow** [comment]
@polavishnu4444 You don't need to pin the protobuf version anymore, it works as is.

**Comment by polavishnu4444** [comment]
@dmahlow - I haven't pinned, seems like the latest stability-sdk has pinned it??
