### ISSUE TITLE
Can expose the API over HTTP? It's hard  for me to use Js Sdk !!! Please 

### ISSUE THREAD

**Issue by romanYI** [Stability-AI/stability-sdk#43]
Can expose the API over HTTP? It's hard  for me to use Js Sdk !!! Please

**Comment by dmarx** [comment]
I've created a 'discussion' thread to centralize discussion regarding requests for an HTTP-supporting API here: https://github.com/Stability-AI/stability-sdk/discussions/51

Please elaborate on the reasons grpc doesn't support your use case there.
