### ISSUE TITLE
Same generation.proto error as before

### ISSUE THREAD

**Issue by theodor38** [Stability-AI/stability-sdk#45]
It might be that I am doing something wrong but I am getting the same error as 3 days ago:

`TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "generation.proto":
  generation.proto: A file with this name is already in the pool.
`
I was really hoping to implement img to img to my application I am developing. Is it that the api interfaces hadn't yet been incorporated to sdk? I just assumed it was since the sdk was updated yesterday.

Thank you in advance for your help.

**Comment by dmarx** [comment]
we're in the process of updating the sdk to depend on the stability-ai/api-interfaces repo as a submodule which will mitigate this sort of thing in the future. for the time being, you can find the most current generation.proto there: https://github.com/Stability-AI/api-interfaces/blob/main/src/proto/generation.proto

**Comment by theodor38** [comment]
Ok, thank you very much for your response!
