### ISSUE TITLE
StabilityInference.generate doesn't supports Sequence[int] as seed

### ISSUE THREAD

**Issue by Thytu** [Stability-AI/stability-sdk#48]
As type hinted [here](https://github.com/Stability-AI/stability-sdk/blob/main/src/stability_sdk/client.py#L212), [StabilityInference.generate](https://github.com/Stability-AI/stability-sdk/blob/main/src/stability_sdk/client.py#L200) should supports a `Sequence[int]` as seed but is overwrited [here](https://github.com/Stability-AI/stability-sdk/blob/main/src/stability_sdk/client.py#L249-L250).

PR in-progress

**Comment by dmarx** [comment]
thanks for the contribution!
