### ISSUE TITLE
No clear means to delete a user account is visible within the beta.dreamstudio.ai user interface

### ISSUE THREAD

**Issue by ebelliveau** [Stability-AI/stability-sdk#6]
Come on, folks.  Stop trying to trap user data forever through shitty UI conventions that don't even allow the user to delete their account _and_ data.

I'm no legal expert, but I'd bet European GDPR specialists would have a field day with your frontend devs.

Let me delete my account.

**Comment by altryne** [comment]
You don't have to be offensive and rude, and open github tickets for irrelevant projects in github. 
This repo is the SDK, not related to the "shitty UI conventions" in any way. 

GDPR doesn't require a button to let you do this, you can contact the company data officer with your request and they have 30 days to delete your data. 

![image](https://user-images.githubusercontent.com/463317/186066342-eefdf2e4-3172-40a3-98a4-57fefd4d72ed.png)

**Comment by dmarx** [comment]
@ebelliveau it sounds like that was a frustrating experience. I've brought this gh issue directly to the attention of our Chief Information Security Officer, who I anticipate will be reaching out to you shortly. I assure you: any failings of our UI are not from designs to trap your data but are rather a function of the accelerated schedule we imposed on ourselves to get these tools out to everyone as quickly as we reasonably could.

**Comment by ebelliveau** [comment]
There.
Is.
No.
User.
Tooling.
To.
Delete.
One's.
Account.

I don't care if it's the SDK; someone in the mix needs to be made aware of this and have the issue passed upwards.  Close it if you must, but I'd rather be heard than sat frustrated trying to accomplish basic auth things with no clear resolution path.

**Comment by ebelliveau** [comment]
> @ebelliveau it sounds like that was a frustrating experience. I've brought this gh issue directly to the attention of our Chief Information Security Officer, who I anticipate will be reaching out to you shortly. I assure you: any failings of our UI are not from designs to trap your data but are rather a function of the accelerated schedule we imposed on ourselves to get these tools out to everyone as quickly as we reasonably could.

Thank you.  I appreciate this.

**Comment by dmarx** [comment]
> Close if it you must 

I'll leave this open until I can be sure the issue is at least being tracked somewhere better and you're in good hands.

**Comment by ebelliveau** [comment]
Right-on.  Thank you, @dmarx.
