### ISSUE TITLE
The API for Image Generation has huge discrepancies between beta.dreamstudio.ai, init_image is discarded

### ISSUE THREAD

**Issue by marius-cristian** [Stability-AI/stability-sdk#62]
Original Image:
![test1](https://user-images.githubusercontent.com/11766613/192547234-7973575e-9d4a-4b2c-bca7-dcb9e341317c.jpg)

Web UI Settings (https://beta.dreamstudio.ai/dream):
wdith/height: 512x512
cfg_scale: 7
steps: 30
sampler: k_lms
model: Stable Difussion 1.5
Seed: 2306870202
prompt: lunar landscape

web ui output:
![dreambeta_variant](https://user-images.githubusercontent.com/11766613/192547295-baedc7ab-c279-4616-80b6-dc157820c4d5.png)

API call settings:
python stability-sdk==0.2.3
```
	img = Image.open(path)
	answers = stability_api.generate(
	    prompt="lunar landscape",
	    init_image=img,
	    mask_image=img,
	    width=512,
	    height=512,
	    seed=2306870202,
	    # safety=False,
	    steps=30, # defaults to 50 if not specified
	    cfg_scale=7.0,
	)
```

API Call Output:
![api_image](https://user-images.githubusercontent.com/11766613/192547686-a14c8af9-7bca-41b2-9655-1e21f42567af.jpg)

API Call Output with mask_image=None
![api_image_no_mask](https://user-images.githubusercontent.com/11766613/192551509-1f76cdfb-9759-4a71-8b69-828a6003575c.jpg)

For some reason, all API calls discard the init_image, and just use the mask_image parameter

I can't seem to make the API calls generate images based on the init_image parameter, there is a big discrepancy between the WebUI and the Library API.

**Comment by marius-cristian** [comment]
I have tried using the sdk version on this github page with commit: caf8365fa503fbb1c727915dee1fae45fa153bc9

And the output is always: https://user-images.githubusercontent.com/11766613/192551509-1f76cdfb-9759-4a71-8b69-828a6003575c.jpg

**Comment by cruhl** [comment]
Here's exactly what's needed to replicate the calls against the gRPC API DreamStudio is making:
```ts
const imageParams = new Generation.ImageParameters();
imageParams.setWidth(this.state?.width ?? 512);
imageParams.setHeight(this.state?.height ?? 512);
imageParams.addSeed(this.state?.seed_enabled ? this.state?.seed : 0);
imageParams.setSamples(Math.max(this.state?.samples ?? 1, 1));
imageParams.setSteps(this.state?.steps ?? 50);

const transformType = new Generation.TransformType();
transformType.setDiffusion(this.state.sampler ?? Generation.DiffusionSampler.SAMPLER_K_LMS);
imageParams.setTransform(transformType);

const request = new Generation.Request();
request.setEngineId(this.state?.model ?? "stable-diffusion-v1-5");
request.setRequestedType(Generation.ArtifactType.ARTIFACT_IMAGE);

request.setClassifier(new Generation.ClassifierParameters());

const samplerParams = new Generation.SamplerParameters();
samplerParams.setCfgScale(this.state.cfgScale);

const stepParams = new Generation.StepParameter();
const scheduleParameters = new Generation.ScheduleParameters();

const png = await this.$refs.editor.renderSVGToPNG("image");
const mask = await this.$refs.editor.renderSVGToPNG("mask");

if (png) scheduleParameters.setStart(mask ? 1 : 1 - this.$refs.editor.generationScheduleStart / 100);

stepParams.setScaledStep(0);
stepParams.setSampler(samplerParams);
stepParams.setSchedule(scheduleParameters);

imageParams.addParameters(stepParams);
request.setImage(imageParams);

const promptText = new Generation.Prompt();
promptText.setText(this.state.prompt);
request.addPrompt(promptText);

if (png) {
  const promptImage = new Generation.Prompt();
  const promptImageParameters = new Generation.PromptParameters();
  const promptImageArtifact = new Generation.Artifact();

  promptImageParameters.setInit(true);
  promptImage.setParameters(promptImageParameters);

  promptImageArtifact.setType(Generation.ArtifactType.ARTIFACT_IMAGE);
  promptImageArtifact.setBinary(await png.blob.arrayBuffer());

  promptImage.setArtifact(promptImageArtifact);
  request.addPrompt(promptImage);

  if (mask) {
    const promptMask = new Generation.Prompt();
    const promptMaskArtifact = new Generation.Artifact();

    promptMaskArtifact.setType(Generation.ArtifactType.ARTIFACT_MASK);
    promptMaskArtifact.setBinary(await mask.blob.arrayBuffer());

    promptMask.setArtifact(promptMaskArtifact);
    request.addPrompt(promptMask);
  }
}
```
I would recommend restructuring things, along with using a different protobuf client generator, but that's how it works currently.

Let me know if you need help getting things working 🤙

**Comment by cruhl** [comment]
In DreamStudio you can run `await editor.renderSVGToPNGDownload("image"); await editor.renderSVGToPNGDownload("mask");` to see the images which are sent as well.

**Comment by marius-cristian** [comment]
Hi @cruhl,

Apparently there is a parameter named:

start_schedule, that controls the similarity of the prompt with the image, and I can see it defaults to 1.0 for the (API)[https://github.com/Stability-AI/stability-sdk/blob/03587c19f1e458a4569ddb0daf68776a377a6e52/src/stability_sdk/client.py#L207]

I managed to generate a very similar image with the one from the web UI, by modifying the start_schedule:

![lunar landscapetest1 jpg](https://user-images.githubusercontent.com/11766613/192695989-4d14080d-73bf-477e-b8b8-392965daf838.jpg)

If I understood correctly 1.0 disregards the image completely. I see the for the CLI it defaults to 0.5
