### ISSUE TITLE
Images generated are extremely poor

### ISSUE THREAD

**Issue by killgt** [Stability-AI/stability-sdk#89]
I'm playing with all parameters, including engine, steps, cfg...  also trying with defaults:

```
python3 -m stability_sdk.client -W 512 -H 512 "A stunning house"
```

Results:
![image](https://user-images.githubusercontent.com/343407/195841780-ebabd655-381a-4b5f-b62b-3be4ea6ecb3a.png)

Other examples from my app:
![image](https://user-images.githubusercontent.com/343407/195841823-60e0d188-7e66-433c-b678-54bb136de991.png)

**Comment by vincentleonIRL** [comment]
Same issue. Updated the SDK version to solve issue #87 but know i'm getting the same kind of Beige images as @killgt here.

**Comment by chigozienri** [comment]
Thanks for the report @killgt and @vincentleonIRL! This is a bug in the 0.2.5 release, we will get a fix out asap - in the mean time you could temporarily downgrade to 0.2.4.
