### ISSUE TITLE
Can JPGs be exported instead of PNGs?

### ISSUE THREAD

**Issue by clipartinc** [Stability-AI/stability-sdk#98]
The file size of JPGs would be much smaller then PNGs. Is this an option?

**Comment by 1MLightyears** [comment]
I'd like to say that's only some aftermath work:
```python3
from PIL import Image
Image.open("<image name>.png").convert("RGB").save("<new name>.jpg")
```
would do the trick.

It's also not bad whatsoeverm if they're willing to implement it built-in, as an option or something else.
